/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
 
    // https://mvnrepository.com/artifact/org.freemarker/freemarker
    testImplementation("org.freemarker:freemarker:2.3.33")

    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.3")

    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.3")

    // https://mvnrepository.com/artifact/org.hamcrest/hamcrest-all
    testImplementation("org.hamcrest:hamcrest-all:1.3")

    // https://mvnrepository.com/artifact/io.rest-assured/rest-assured
    testImplementation("io.rest-assured:rest-assured:5.5.0")

    // https://mvnrepository.com/artifact/io.rest-assured/json-schema-validator
    testImplementation("io.rest-assured:json-schema-validator:5.5.0")

    // https://mvnrepository.com/artifact/io.qameta.allure/allure-junit5
    testImplementation("io.qameta.allure:allure-junit5:2.29.0")
    
    // https://mvnrepository.com/artifact/io.qameta.allure/allure-attachments
    testImplementation("io.qameta.allure:allure-attachments:2.29.0")

    // https://mvnrepository.com/artifact/io.qameta.allure/allure-rest-assured
    testImplementation("io.qameta.allure:allure-rest-assured:2.29.0")

    // https://mvnrepository.com/artifact/io.qameta.allure/allure-attachments
    testImplementation("io.qameta.allure:allure-attachments:2.28.1")
    
    // https://mvnrepository.com/artifact/io.qameta.allure/allure-java-commons
    testImplementation("io.qameta.allure:allure-java-commons:2.29.0")
    
    // https://mvnrepository.com/artifact/org.junit.platform/junit-platform-suite-engine
    testImplementation("org.junit.platform:junit-platform-suite-engine:1.10.3")
    
    // https://mvnrepository.com/artifact/org.junit.platform/junit-platform-suite
    testImplementation("org.junit.platform:junit-platform-suite:1.10.3")
    
    // https://mvnrepository.com/artifact/org.junit.platform/junit-platform-suite-api
    testImplementation("org.junit.platform:junit-platform-suite-api:1.10.3")
    
    // https://mvnrepository.com/artifact/org.junit.platform/junit-platform-runner
    testImplementation("org.junit.platform:junit-platform-runner:1.10.0")

    // https://mvnrepository.com/artifact/com.github.javafaker/javafaker
    testImplementation("com.github.javafaker:javafaker:1.0.2")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
